### ISSUE TITLE
How long does it take to execute vector-space model?

### ISSUE THREAD

**Issue by plumlike** [FutureGadget/COSE472_Information_Retrieval#2]

**Comment by FutureGadget** [comment]
It can be further optimized by using a map data structure not to read inverted index file.
Currently, without that optimization, It takes about 107 secs and the MAP is about 0.4.

![image](https://cloud.githubusercontent.com/assets/11131630/20456937/3f05b05a-aec4-11e6-980b-6922ce1b707f.png)

![image](https://cloud.githubusercontent.com/assets/11131630/20456944/53a03436-aec4-11e6-87c7-02c4a83823a5.png)
